version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: jogos-postgres-dev
    environment:
      POSTGRES_DB: jogos
      POSTGRES_USER: jogos
      POSTGRES_PASSWORD: jogos123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - jogos-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jogos -d jogos"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: jogos-app-dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://jogos:jogos123@postgres:5432/jogos
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - jogos-network-dev
    restart: unless-stopped
    command: npm run dev

volumes:
  postgres_data_dev:

networks:
  jogos-network-dev:
    driver: bridge 